### ISSUE TITLE
Weak Frechet distance

### ISSUE THREAD

**Issue by aniketmitra001** [heremaps/movetk#20]

**Comment by aniketmitra001** [comment]
@bacusters  can you please share the reference material based on which you implemented the  Weak Frechet Distance algorithm?

**Comment by bacusters** [comment]
@aniketmitra001 It is based on the original Frechet distances paper by Alt and Godau: http://www.staff.science.uu.nl/~kreve101/asci/ag-cfdbt-95.pdf. I'll add it to the source code. I'll also fix the DCO problems!

**Comment by bacusters** [comment]
Moving the algorithm to Distances.h requires #33 to be solved.
