### ISSUE TITLE
Algorithms in Statistics.h have a tight coupling with TabularTrajectory and ColumnarTrajectory types

### ISSUE THREAD

**Issue by aniketmitra001** [heremaps/movetk#41]
The implementation of algorithms in ```movetk/algo/Statistics.h``` assumes that the input trajectory is  of type ```TabularTrajectory``` or ```ColumnarTrajectory```.  

However, sometimes the  trajectory type may not necessarily be of these two types, for example the return type of ```Splitter::begin()```

So maybe its better to use ``TrajectoryTraits``` to infer the type of a particular field instead of using ```typename Trajectory::template FieldType<TimeStampIdx>```

**Comment by bacusters** [comment]
Good point. I'm not entirely sure on how to use the TrajectoryTraits to infer how to iterate over the probe points for the trajectory. Do you have a suggestion how to do that?

**Comment by bacusters** [comment]
Closed by #44
